[package]
name = "minsweeper-rs"
version = "1.0.0"
edition = "2024"

description = "Rust implementation of minsweeper"

readme = "README.md"
repository = "https://github.com/Canary-Prism/minsweeper-rs"
license = "Apache-2.0"

[dependencies]
rand = "0.9.2"
linked_hash_set = "0.1.6"